[[constraint]]
  name = "github.com/pulumi/pulumi"
  version = "1.13.0"

[[constraint]]
  name = "github.com/pulumi/pulumi-aws"
  version = "1.27.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.29.10"

[prune]
  go-tests = true
  unused-packages = true
